app/routes/admin_routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from flask_login import login_required
from app.extensions import db
from app.models.announcements import Announcement
from app.models.complaints import Complaint
from app.utils.roles import admin_required
from app.models.announcements import Notification
from flask_login import current_user

admin_bp = Blueprint("admin", __name__, url_prefix="/admin")

# --------------dashboard-----------------
@admin_bp.route("/dashboard")
@login_required
@admin_required
def dashboard():
    hostel = request.args.get("hostel")
    if hostel:
        complaints = Complaint.query.filter_by(hostel=hostel).all()
    else:
        complaints = Complaint.query.all()
    return render_template(
        "admin/dashboard.html",
        complaints=complaints,
        selected_hostel=hostel
    )



# ---------------------announcements------------------------------------
@admin_bp.route("/announcements", methods=["GET", "POST"])
@login_required
@admin_required
def announcements():
    if request.method == "POST":
        a = Announcement(
            title=request.form["title"],
            message=request.form["message"],
            hostel=request.form.get("hostel"),
            is_pinned=True if request.form.get("pin") else False
        )
        db.session.add(a)
        db.session.commit()

        
        n = Notification(
            message=f"{a.title} — {a.message[:80]}...",
            user_id=current_user.id  
        )
        db.session.add(n)
        db.session.commit()

        flash("Announcement published", "success")
        return redirect(url_for("admin.announcements"))

    announcements = Announcement.query.order_by(
        Announcement.is_pinned.desc(),
        Announcement.created_at.desc()
    ).all()

    return render_template("admin/announcements.html", announcements=announcements)





# ------------------------update_status--------------------
@admin_bp.route("/complaint/<int:id>/status", methods=["POST"])
@login_required
@admin_required
def update_status(id):
    complaint = Complaint.query.get_or_404(id)
    complaint.status = request.form["status"]
    db.session.commit()
    return redirect(request.referrer)





# -----------------edit_announcement------------------------
@admin_bp.route("/announcement/edit/<int:id>", methods=["GET", "POST"])
@admin_required
def edit_announcement(id):
    a = Announcement.query.get_or_404(id)

    if request.method == "POST":
        a.title = request.form["title"]
        a.message = request.form["message"]
        a.hostel = request.form.get("hostel")
        a.is_pinned = True if request.form.get("pin") else False
        db.session.commit()
        flash("Announcement updated", "success")
        return redirect(url_for("admin.announcements"))

    return render_template("admin/edit_announcement.html", a=a)




# ------------------delete_announcement------------------------
@admin_bp.route("/announcement/delete/<int:id>")
@admin_required
def delete_announcement(id):
    a = Announcement.query.get_or_404(id)
    db.session.delete(a)
    db.session.commit()
    flash("Announcement deleted", "danger")
    return redirect(url_for("admin.announcements"))


# ------------hostel_wardens----------------
@admin_bp.route("/hostel_wardens")
def hostel_wardens():
    return render_template("publics/hostel_wardens.html")

app/routes/auth_routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from ..forms import RegistrationForm, LoginForm
from ..extensions import db, bcrypt
from ..models.user import User
from flask_login import login_user, current_user, logout_user



auth_bp = Blueprint("auth", __name__)

# -----------------------register-----------------------------
@auth_bp.route("/")
def home1():
    return redirect(url_for("auth.register"))


@auth_bp.route("/register", methods=["GET", "POST"])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data
        ).decode("utf-8")
        user = User(
            username=form.username.data,
            email=form.email.data,
            password=hashed_password,
            hostel=form.hostel.data,
            room_no=form.room_no.data
        )
        db.session.add(user)
        db.session.commit()
        flash("Account created successfully", "success")
        return redirect(url_for("auth.login"))
    return render_template("auth/register.html", form=form)





# ------------------ Login ------------------
@auth_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('auth.home'))
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash("Welcome back!", "success")
            return redirect(next_page) if next_page else redirect(url_for('auth.home'))

        flash("Invalid username or password", "danger")

    return render_template("auth/login.html", title="login", form=form)




# ------------------ Home ------------------
@auth_bp.route("/home")
def home():
    return render_template("auth/home.html")



# --------------------logout_user---------------
@auth_bp.route("/logout")
def logout():
    logout_user()
    flash("Logged out successfully", "info")
    return redirect(url_for("auth.login"))

app/routes/chatbot.py
from flask import Blueprint, request, jsonify, render_template
from flask_login import login_required
from app.utils.ai_chatbot import get_ai_reply

chatbot_bp = Blueprint("chatbot", __name__)

@chatbot_bp.route("/chatbot", methods=["GET"])
@login_required
def chatbot_page():
    return render_template("hostel/chatbot.html")

@chatbot_bp.route("/chatbot/message", methods=["POST"])
@login_required
def chatbot_message():
    data = request.get_json()

    if not data or "message" not in data:
        return jsonify({"reply": "⚠️ Invalid request"}), 400

    user_msg = data["message"].strip()

    if not user_msg:
        return jsonify({"reply": "⚠️ Please enter a message"}), 400

    try:
        reply = get_ai_reply(user_msg)
    except Exception as e:
        print(f"[AI ERROR] {e}")
        reply = "⚠️ AI service is temporarily unavailable."

    return jsonify({"reply": reply}), 200

app/routes/students_routes.py
# ==============================importing all_stuffs=====================================================
from flask import Blueprint, jsonify, render_template, flash, redirect, url_for, request, abort
from flask_login import login_required, current_user
from sqlalchemy import func
from ..extensions import db
from ..models.user import User
from ..models.complaints import Complaint, ComplaintUpvote, HostelDiary
from ..forms import ComplaintForm
import os
import uuid
from app.models.announcements import Notification
from flask import current_app
from werkzeug.utils import secure_filename

students_bp = Blueprint('students', __name__)





# -------------------------------------my complaints-------------------------------------
@students_bp.route('/my_complaints')
@login_required
def my_complaints():
    user_complaints = Complaint.query.filter_by(user_id=current_user.id).all()
    
    if not user_complaints:
        flash("Empty", "info")
        return redirect(url_for('students.report_issue')) 
    
    return render_template('student/my_issues.html', complaints=user_complaints)




# ----------------------------report issue--------------------------------
@students_bp.route("/report_issue", methods=['GET', 'POST'])
@login_required
def report_issue():
    form = ComplaintForm()

    if form.validate_on_submit():
        image_filename = None

       
        if form.image.data:
            image = form.image.data
            image_filename = f"{uuid.uuid4().hex}_{secure_filename(image.filename)}"

            upload_folder = os.path.join(
                current_app.root_path,
                "static/complaint_images"
            )

            
            os.makedirs(upload_folder, exist_ok=True)

          
            image.save(os.path.join(upload_folder, image_filename))

       
        new_issue = Complaint(
            category=form.category.data,
            description=form.description.data,
            image=image_filename,
            user_id=current_user.id,
            hostel=current_user.hostel 
        )

        db.session.add(new_issue)
        db.session.commit()

        flash('Your issue has been reported successfully!', 'success')
        return redirect(url_for('students.my_complaints'))

    return render_template('student/report_issue.html', form=form)


# ================================dashboard==============================
@students_bp.route("/dashboard")
@login_required
def dashboard():
    hostel = current_user.hostel

    complaints = Complaint.query.filter_by(hostel=hostel).all()

    return render_template(
        "student/dashboard.html",
        complaints=complaints,
        hostel=hostel
    )
    
    
# =====================================schedules================================ 
@students_bp.route("/schedules")
@login_required
def schedules():
    return render_template("publics/schedules.html")
    
    

# --------------------------------about----------------------------
@students_bp.route("/about")
@login_required
def about():
    return render_template("publics/about.html")

# -----------------------------------------hostel_facility-------------------------------
@students_bp.route("/hostel_facility")
@login_required
def hostel_facility():
    return render_template("hostel/hostel_facility.html")



    
    
# ------------------------------issues-----------------------------------
@students_bp.route("/issues")
@login_required
def all_issues():

    if current_user.role == 'admin':
        complaints = Complaint.query.order_by(Complaint.upvotes.desc()).all()
        hostel = "All Hostels"
    else:
        complaints = Complaint.query.filter_by(
            hostel=current_user.hostel
        ).order_by(Complaint.upvotes.desc()).all()
        hostel = current_user.hostel

    return render_template(
        "publics/all_issues.html",
        complaints=complaints,
        hostel=hostel
    )





# ------------------------------------notififcation------------------------------------
@students_bp.route("/notification")
@login_required
def notification():
    notifications = Notification.query.order_by(
        Notification.created_at.desc()
    ).all()

    return render_template(
        "publics/notification.html",
        notifications=notifications
    )
    
# -------------------delete_notification---------------------
@students_bp.route("/notifications/delete/<int:id>", methods=["POST"])
@login_required
def delete_notification(id):
    notification = Notification.query.get_or_404(id)
    db.session.delete(notification)
    db.session.commit()
    flash("Notification removed", "success")
    return redirect(url_for("students.notification"))


# -------------------------------clear_notifications-------------------
@students_bp.route("/clear_notifications", methods=["POST"])
@login_required
def clear_notifications():
    # Delete all notifications for the logged-in user
    try:
        Notification.query.filter_by(user_id=current_user.id).delete()
        db.session.commit()
        flash("All notifications cleared successfully.", "success")
    except Exception as e:
        db.session.rollback()
        flash("Error clearing notifications.", "danger")
        print(e)
    
    return redirect(url_for("students.notification"))




    
# -----------------------------------------analytics----------------------------------
@students_bp.route('/analytics')
@login_required
def analytics():

    is_admin = current_user.role == 'admin'

    # ---------- STATUS COUNTS ----------
    status_query = db.session.query(
        Complaint.status,
        func.count(Complaint.id)
    )

    if not is_admin:
        status_query = status_query.filter(
            Complaint.hostel == current_user.hostel
        )

    status_data = status_query.group_by(Complaint.status).all()

    status_counts = {
        "Pending": 0,
        "In Progress": 0,
        "Resolved": 0
    }

    for status, count in status_data:
        status_counts[status] = count


    # ---------- CATEGORY COUNTS ----------
    category_query = db.session.query(
        Complaint.category,
        func.count(Complaint.id)
    )

    if not is_admin:
        category_query = category_query.filter(
            Complaint.hostel == current_user.hostel
        )

    category_data = category_query.group_by(Complaint.category).all()

    categories = [c for c, _ in category_data]
    category_counts = [count for _, count in category_data]


    # ---------- TOTAL UPVOTES ----------
    upvote_query = db.session.query(
        func.count(ComplaintUpvote.id)
    ).join(Complaint)

    if not is_admin:
        upvote_query = upvote_query.filter(
            Complaint.hostel == current_user.hostel
        )

    total_upvotes = upvote_query.scalar() or 0


    # ------------------- TOTAL ISSUES -----------------
    issues_query = Complaint.query

    if not is_admin:
        issues_query = issues_query.filter(
            Complaint.hostel == current_user.hostel
        )

    total_issues = issues_query.count()


    # ---------------------- TOP ISSUES -----------------------
    top_query = Complaint.query.order_by(
        Complaint.upvotes.desc()
    )

    if not is_admin:
        top_query = top_query.filter(
            Complaint.hostel == current_user.hostel
        )

    top_issues = top_query.limit(5).all()

    top_issues_data = [
        {
            "category": issue.category,
            "upvotes": issue.upvotes
        }
        for issue in top_issues
    ]


    return render_template(
        "publics/analytics.html",
        status_counts=status_counts,
        categories=categories,
        category_counts=category_counts,
        total_upvotes=total_upvotes,
        total_issues=total_issues,
        top_issues=top_issues_data,
        hostel="All Hostels" if is_admin else current_user.hostel
    )



# ===========================upvote_complaint=====================================
@students_bp.route('/complaint/<int:cid>/upvote', methods=['POST'])
@login_required
def upvote_complaint(cid):

    complaint = Complaint.query.get_or_404(cid)

    
    existing = ComplaintUpvote.query.filter_by(
        user_id=current_user.id,
        complaint_id=cid
    ).first()

    if existing:
        return jsonify({'success': False, 'error': 'Already voted'})

    # add vote
    vote = ComplaintUpvote(
        user_id=current_user.id,
        complaint_id=cid
    )

    complaint.upvotes += 1

    db.session.add(vote)
    db.session.commit()

    return jsonify({
        'success': True,
        'upvotes': complaint.upvotes
    })



# ================diary delete=============================
@students_bp.route('/delete-diary/<int:id>')
@login_required
def delete_diary(id):
    diary = HostelDiary.query.get_or_404(id)

    if diary.user_id != current_user.id:
        flash("You can't delete this photo", "danger")
        return redirect(url_for('students.profile'))

    image_path = os.path.join('app/static/uploads', diary.image)
    if os.path.exists(image_path):
        os.remove(image_path)

    db.session.delete(diary)
    db.session.commit()

    flash("Diary deleted successfully", "success")
    return redirect(url_for('students.profile'))




# ------------------delete_issues---------------------------
@students_bp.route('/delete-issues')
@login_required
def delete_issues():
    id = request.args.get('id', type=int)

    if not id:
        abort(404)

    issue = Complaint.query.get_or_404(id)

    if issue.user_id != current_user.id:
        flash("You are not allowed to delete this complaint.", "danger")
        return redirect(url_for('students.my_complaints'))

    # delete image if exists
    if issue.image:
        image_path = os.path.join(
            current_app.root_path,
            'static/complaint_images',
            issue.image
        )
        if os.path.exists(image_path):
            os.remove(image_path)

    db.session.delete(issue)
    db.session.commit()

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {%block title%}CITK HOSTEL MANAGEMENT SYSTEM{%endblock%}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css')}}">

    <script src="{{ url_for('static', filename='js/script.js') }}" defer></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script src="{{ url_for('static', filename='js/analytics.js') }}"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css" integrity="sha512-2SwdPD6INVrV/lHTZbO2nodKhrnDdJK9/kg2XD1r9uGqPo1cUbujc+IYdlYdEErWNu69gVcYgdxlmVmzTWnetw==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>

<script>
document.addEventListener("DOMContentLoaded", function () {
    const megaParents = document.querySelectorAll(".sp-mega-parent");

    megaParents.forEach(parent => {
        const link = parent.querySelector("a");

        link.addEventListener("click", function (e) {
            if (window.innerWidth <= 900) {
                e.preventDefault();

               
                megaParents.forEach(p => {
                    if (p !== parent) p.classList.remove("active");
                });

                parent.classList.toggle("active");
            }
        });
    });

    
    document.addEventListener("click", function (e) {
        if (window.innerWidth <= 900) {
            megaParents.forEach(parent => {
                if (!parent.contains(e.target)) {
                    parent.classList.remove("active");
                }
            });
        }
    });
});
</script>


<body>


    <header>
         <div class="top-bar">
        <div class="top-container" style="height: 35px;">
            <div class="top-left">
                <span id="typing-text"></span>
                <span class="cursor"></span>
            </div>

            <div class="top-right">
                <a href="{{ url_for('students.profile') }}">
                    <i class="fa-solid fa-user"></i>
                    <span>My Profile</span>
                </a>
                <a href="{{ url_for('auth.logout') }}">
                    <i class="fa-solid fa-right-from-bracket"></i>
                    <span>Logout</span>
                </a>
                
            </div>
        </div>
    </div>

   
    <div class="branding-section">
        <div class="branding-container">
            <img src="{{ url_for('static', filename='images/citk_logo.png') }}"
                 alt="CITK Logo"
                 class="main-logo">

            <div class="title-text">
                <h1>सीआईटीके छात्रावास प्रबंधन प्रणाली</h1>
                <h2>CITK HOSTEL MANAGEMENT SYSTEM</h2>
                <p>Deemed to be University under MoE, Govt. of India</p>
            </div>
        </div>
    </div>

        
        <nav class="sp-main-nav">
            <div class="nav-header">
        <button class="mobile-menu-toggle" aria-label="Open Menu">
            <span class="bar" style="margin: 2px 0px;"></span>
            <span class="bar"></span>
            <span class="bar"></span>
        </button>
    </div>
            <ul class="sp-nav-list">
                <li class="mobile-only close-row">
            <button class="close-menu">&times; Close</button>
        </li>

            <li><a href="{{ url_for('auth.home') }}">Home</a></li>

            {% if current_user.role == 'student' %}
                <li><a href="{{ url_for('students.report_issue') }}">Report Issue</a></li>
                <li><a href="{{ url_for('students.my_complaints') }}">My Reported Issues</a></li>
            {% endif %}

            <li><a href="{{ url_for('students.all_issues') }}">All Issues</a></li>
            <li><a href="{{ url_for('students.analytics') }}">Analytics</a></li>

            {% if current_user.role == 'admin' %}
                <li><a href="{{ url_for('admin.announcements') }}">Announcements</a></li>
            {% endif %}


        <!-- MEGA MENU -->
        <li class="sp-mega-parent">
            <a href="#" class="mobile-trigger">Resources ▾</a>

            <div class="sp-mega-box">
                <div class="sp-mega-left">
                    <h4>Hostel Resources</h4>
                    <ul>
                        <li><a href="#">Hostel Rules</a></li>
                        <li><a href="{{ url_for('students.schedules')}}">Schedules</a></li>
                        <li><a href="{{ url_for('students.hostel_body')}}">Hostel Bodies</a></li>
                        <li><a href="{{ url_for('admin.hostel_wardens') }}">Hostel Wardens</a></li>
                        
                        
                        
                    </ul>
                </div>

                <div class="sp-mega-right">
                    <h4>Others</h4>
                    <div class="sp-mega-grid">
                        
                        <a href="{{url_for('students.anti_ragging')}}">Anti Ragging</a>
                        <a href="#">Notices</a>

                        
                    </div>
                </div>
            </div>
        </li>

        <li class="sp-mega-parent">
            <a href="#" class="mobile-trigger">More▾</a>

            <div class="sp-mega-box">
                <div class="sp-mega-left">
                    <h4>Important</h4>
                    <ul>
                        
                        <li><a href="https://cit.ac.in/pages-uploads-academic-form">Forms</a></li>
                         {% if current_user.role == 'admin' %}
                        <li><a href="{{url_for('students.hostel_rooms')}}">Hostel Rooms </a></li>
                        {% endif %}
                        <li><a href="{{url_for('diary.hostel_diaries')}}">Hostel Diaries</a></li>
                        
                        
                    </ul>
                </div>

                <div class="sp-mega-right">
                    <h4>Others</h4>
                    <div class="sp-mega-grid">
                        
                        <a href="{{url_for('students.organizational_structure')}}">Organizational Structure</a>
                        <a href="{{url_for('students.hostel_facility')}}">Hostel Facility</a>
                        <a href="{{url_for('students.help')}}">Help</a>
                        <a href="{{url_for('students.feedback')}}">Send Feedback</a>

                        
                    </div>
                </div>
            </div>
        </li>
        <li>
            <a href="{{url_for('students.notification')}}" class="sp-badge-link">
               Notifications <span class="sp-badge">{{ notification_count }}</span>

            </a>
        </li>

        <li><a href="{{url_for('students.about')}}">About</a></li>
        <li class="nav-item"><a href="{{ url_for('chatbot.chatbot_page') }}" class="nav-link">
    Hostel Bot
</a>
</li>

        
        
            </ul>
        </nav>
    </header>
    
        {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        <div class="flash {{ category }}" style="background-color:#d7e6d0">{{ message }}!</div>
        {% endfor %}
    {% endif %}
    {% endwith %}

    {% block content%}
    <main class="container">
        <section class="welcome-section">
            <h3>Welcome to the Hostel Management Portal</h3>
            <p>Select an option from the menu above or write to report a new maintenance or security issue.</p>
        </section>
    </main>
    {%endblock%}
    
    
 
    <button id="backToTop" title="Go to top">↑</button>

    <footer class="citk-footer">
        <div class="footer-container">
            
        <div class="footer-about">
            <img src="{{ url_for('static', filename='images/citk_logo.png') }}" alt="CITK Logo">
            <h3>Central Institute of Technology</h3>
            <p>Kokrajhar - 783370, Assam, India</p>
            <p class="email">📧 XXXXXXXX.cit.ac.in</p>
            
            <div class="social-icons">
                <a href="#"><i class="fab fa-facebook-f"></i></a>
                <a href="#"><i class="fab fa-twitter"></i></a>
            </div>
        </div>
        
       
        <div class="footer-links">
            <h4>Quick Links</h4>
            <ul>
                <li><a href="{{url_for('auth.home')}}">Home</a></li>
                
                <li><a href="{{url_for('students.my_complaints')}}">My Reported Issue</a></li>
                <li><a href="{{url_for('admin.hostel_wardens')}}">Hostel Wardens</a></li>
                <li><a href="{{url_for('students.about')}}">About</a></li>
                
            </ul>
        </div>
        
    
        <div class="footer-links">
            <h4>Important Links</h4>
            <ul>
                <li><a href="{{url_for('students.anti_ragging')}}">Anti Ragging</a></li>
                <li><a href="{{url_for('students.report_issue')}}">Report Issue</a></li>
                <li><a href="#">Hostel Rules</a></li>
                
            </ul>
        </div>
    </div>
    
    
    <div class="footer-bottom">
        <p style="line-height: 1.4;">
           This website is developed for training and academic purposes only.
            It is not an official system of Central Institute of Technology, Kokrajhar.
            Official deployment will be considered only after institutional approval.
        </p>
        <p class="copyright">
            © 2025 Central Institute of Technology Kokrajhar
        </p>
    </div>
</footer>







    <script>

    document.addEventListener("DOMContentLoaded", () => {
    const text = "CITK | HOSTEL PORTAL";
    const container = document.getElementById("typing-text");
    let index = 0;

    function play() {
        if (index < text.length) {
            container.textContent += text[index];
            index++;
            setTimeout(play, 900);
        } else {
            setTimeout(() => {
                container.textContent = "";
                index = 0;
                play();
            }, 1000);
        }
    }

    play();
});
</script>

<script>
    const backToTopBtn = document.getElementById("backToTop");

    window.addEventListener("scroll", () => {
        if (window.scrollY > 300) {
            backToTopBtn.style.display = "block";
        } else {
            backToTopBtn.style.display = "none";
        }
    });

    backToTopBtn.addEventListener("click", () => {
        window.scrollTo({
            top: 0,
            behavior: "smooth"
        });
    });
</script>



<script>

document.addEventListener('DOMContentLoaded', function() {
    const toggleBtn = document.querySelector('.mobile-menu-toggle');
    const closeBtn = document.querySelector('.close-menu');
    const navList = document.querySelector('.sp-nav-list');
    const triggers = document.querySelectorAll('.mobile-trigger');

    
    if (toggleBtn) {
        toggleBtn.addEventListener('click', function() {
            navList.classList.add('is-active');
        });
    }

    
    if (closeBtn) {
        closeBtn.addEventListener('click', function() {
            navList.classList.remove('is-active');
        });
    }

   
   
triggers.forEach(trigger => {
    trigger.addEventListener('click', function(e) {
        if (window.innerWidth <= 992) {
            e.preventDefault();
            e.stopPropagation();
            const parent = this.parentElement;
            
            
            parent.classList.toggle('is-open');
        }
    });
});


});
</script>




</body>
</html>